### ISSUE TITLE
Casting

### ISSUE THREAD

**Issue by Naddiseo** [lukescott/es-type-hinting#15]
Casting is usually done for the benefit of the linter / type checker.

One possible alternate is presented in #2, to use `NewType(oldValue)`, unfortunately, this has a runtime cost, and may have side effects if `oldValue` has `.toString` or `.valueOf` depending on what the casting type is.

Other precedents, both of which incur no runtime cost:
typescript: `var a = <NewType>oldA;`
dart: `var a = (oldA as NewType);`

What are the downsides to having no type casting? What limitations does it incur?

**Comment by lukescott** [comment]
It really depends on who is responsible for checking the type: The engine or a linter.
- If the engine, this all happens at runtime, so casting is not needed.
- If the linter, it can really do it's best guess. External code is also an area this could fail in.

**Comment by Naddiseo** [comment]
Let's track the responsibility in #9.

**Comment by Naddiseo** [comment]
(refs #30): I think this falls out of scope. If at some point in the future, the tool/linter creators ask for casting, then we can revisit the issue, or create a new spec. Closing for now.
