### ISSUE TITLE
Untagged issues

### ISSUE THREAD

**Issue by lukescott** [lukescott/es-type-hinting#30]
@Naddiseo which of these do we still need?
#5 Type of Rest and Spread - close? Did we cover this already?
#6 Generics - should we cover syntax for this? leave it to compilers like babel?
#7 Type aliases - don't need to cover that?
#8 Are classes new types - close? Yes?
#12 TypeHint on setter - and getter? Do we still need to resolve this?
#13 Nullable and optional - close? Strictly that type, and we have default func args, right?
#14 any and void - close? We have void func return. Anything else?
#15 Casting - close? Not needed?

Added you as a collaborator, so that should mean you can push/tag/merge stuff.

**Comment by Naddiseo** [comment]
I've gone through and tagged the other issues.

Thanks. I'll refrain from merging anything more than typo fixes until you've also looked over any changes with a  "LGTM".

**Comment by lukescott** [comment]
Cool, thanks for doing that. Sounds good.
