### ISSUE TITLE
Overloading

### ISSUE THREAD

**Issue by Naddiseo** [lukescott/es-type-hinting#35]
How would we handle overloading?

``` javascript
var o = {
    add: function(arg1 number, arg2 number) {},
    add: function(arg1 string, arg2 string) {} // this replaces the key in o.
};
```

**Comment by Naddiseo** [comment]
I'm thinking it's just simpler to say "we don't handle overloading", since the language doesn't support it, and adding it to a dynamic languages doesn't make much sense. The the way dynamic languages get around this is by using union types... but then we start getting into weird stuff when it comes to reflection: the language would need a `@@unionType` primitive.

**Comment by lukescott** [comment]
Yeah, I think it would be rather difficult (impossible?) to do overloading without strict typing.

**Comment by Naddiseo** [comment]
Closing. It's not something we need to handle because it's expected behaviour in javascript to shadow methods/variables.
